[package]
name = "trustfall_git_adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.3"
trustfall = "0.8.1"
trustfall_core = "0.8.1"
trustfall_derive = "0.3.1"

[dev-dependencies]
tempfile = "3.8"
